import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className='container'>
            <div className='row'>
              <div className='col'>
                <h1 className='text-center mb-4'>Welcome Poke App!</h1>
              </div>
            </div>
            <div className='row'>
              <div className='col'>
                {children}
              </div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
